#python main.py --config config/sign/train/train_joint.yaml
  #num_class: 28 # AEC=28, PUCP=29 , WLASL=86

  #num_point: 29 # 29 or 71

'''
python main.py --experiment_name results/f_29/PUCP/cris_wholepose_PUCP --database PUCP --keypoints_model wholepose --base_lr 0.001 --num_class 29 --keypoints_number 29 --num_epoch 5 --training_set_path ../../../cristian/dataset_original/PUCP_PSL_DGI156--wholepose-Train.hdf5 --testing_set_path ../../../cristian/dataset_original/PUCP_PSL_DGI156--wholepose-Val.hdf5 --config config/sign/train/train_joint.yaml 
python main.py --experiment_name results/f_29/PUCP/cris_mediapipe_PUCP --database PUCP --keypoints_model mediapipe --base_lr 0.001 --num_class 29 --keypoints_number 29 --num_epoch 5 --training_set_path ../../../cristian/dataset_original/PUCP_PSL_DGI156--mediapipe-Train.hdf5 --testing_set_path ../../../cristian/dataset_original/PUCP_PSL_DGI156--mediapipe-Val.hdf5 --config config/sign/train/train_joint.yaml 
python main.py --experiment_name results/f_29/PUCP/cris_openpose_PUCP --database PUCP --keypoints_model openpose --base_lr 0.001 --num_class 29 --keypoints_number 29 --num_epoch 5 --training_set_path ../../../cristian/dataset_original/PUCP_PSL_DGI156--openpose-Train.hdf5 --testing_set_path ../../../cristian/dataset_original/PUCP_PSL_DGI156--openpose-Val.hdf5 --config config/sign/train/train_joint.yaml 

python main.py --experiment_name results/f_29/WLASL/cris_wholepose_WLASL --database WLASL --keypoints_model wholepose --base_lr 0.001 --num_class 86 --keypoints_number 29 --num_epoch 5 --training_set_path ../../../cristian/dataset_original/WLASL--wholepose-Train.hdf5 --testing_set_path ../../../cristian/dataset_original/WLASL--wholepose-Val.hdf5 --config config/sign/train/train_joint.yaml 
python main.py --experiment_name results/f_29/WLASL/cris_mediapipe_WLASL --database WLASL --keypoints_model mediapipe --base_lr 0.001 --num_class 86 --keypoints_number 29 --num_epoch 5 --training_set_path ../../../cristian/dataset_original/WLASL--mediapipe-Train.hdf5 --testing_set_path ../../../cristian/dataset_original/WLASL--mediapipe-Val.hdf5 --config config/sign/train/train_joint.yaml 
python main.py --experiment_name results/f_29/WLASL/cris_openpose_WLASL --database WLASL --keypoints_model openpose --base_lr 0.001 --num_class 86 --keypoints_number 29 --num_epoch 5 --training_set_path ../../../cristian/dataset_original/WLASL--openpose-Train.hdf5 --testing_set_path ../../../cristian/dataset_original/WLASL--openpose-Val.hdf5 --config config/sign/train/train_joint.yaml 


python main.py --experiment_name results/f_29/AEC/cris_wholepose_AEC --database AEC --keypoints_model wholepose --base_lr 0.001 --num_class 28 --keypoints_number 29 --num_epoch 5 --training_set_path ../../../cristian/dataset_original/AEC--wholepose-Train.hdf5 --testing_set_path ../../../cristian/dataset_original/AEC--wholepose-Val.hdf5 --config config/sign/train/train_joint.yaml 
python main.py --experiment_name results/f_29/AEC/cris_mediapipe_AEC --database AEC --keypoints_model mediapipe --base_lr 0.001 --num_class 28 --keypoints_number 29 --num_epoch 5 --training_set_path ../../../cristian/dataset_original/AEC--mediapipe-Train.hdf5 --testing_set_path ../../../cristian/dataset_original/AEC--mediapipe-Val.hdf5 --config config/sign/train/train_joint.yaml 
python main.py --experiment_name results/f_29/AEC/cris_openpose_AEC --database AEC --keypoints_model openpose --base_lr 0.001 --num_class 28 --keypoints_number 29 --num_epoch 5 --training_set_path ../../../cristian/dataset_original/AEC--openpose-Train.hdf5 --testing_set_path ../../../cristian/dataset_original/AEC--openpose-Val.hdf5 --config config/sign/train/train_joint.yaml 


python main.py --experiment_name results/f_71/PUCP/cris_wholepose_PUCP --database PUCP --keypoints_model wholepose --base_lr 0.001 --num_class 29 --keypoints_number 71 --num_epoch 5 --training_set_path ../../../cristian/dataset_original/PUCP_PSL_DGI156--wholepose-Train.hdf5 --testing_set_path ../../../cristian/dataset_original/PUCP_PSL_DGI156--wholepose-Val.hdf5 --config config/sign/train/train_joint.yaml 
python main.py --experiment_name results/f_71/PUCP/cris_mediapipe_PUCP --database PUCP --keypoints_model mediapipe --base_lr 0.001 --num_class 29 --keypoints_number 71 --num_epoch 5 --training_set_path ../../../cristian/dataset_original/PUCP_PSL_DGI156--mediapipe-Train.hdf5 --testing_set_path ../../../cristian/dataset_original/PUCP_PSL_DGI156--mediapipe-Val.hdf5 --config config/sign/train/train_joint.yaml 
python main.py --experiment_name results/f_71/PUCP/cris_openpose_PUCP --database PUCP --keypoints_model openpose --base_lr 0.001 --num_class 29 --keypoints_number 71 --num_epoch 5 --training_set_path ../../../cristian/dataset_original/PUCP_PSL_DGI156--openpose-Train.hdf5 --testing_set_path ../../../cristian/dataset_original/PUCP_PSL_DGI156--openpose-Val.hdf5 --config config/sign/train/train_joint.yaml 

python main.py --experiment_name results/f_71/WLASL/cris_wholepose_WLASL --database WLASL --keypoints_model wholepose --base_lr 0.001 --num_class 86 --keypoints_number 71 --num_epoch 5 --training_set_path ../../../cristian/dataset_original/WLASL--wholepose-Train.hdf5 --testing_set_path ../../../cristian/dataset_original/WLASL--wholepose-Val.hdf5 --config config/sign/train/train_joint.yaml 
python main.py --experiment_name results/f_71/WLASL/cris_mediapipe_WLASL --database WLASL --keypoints_model mediapipe --base_lr 0.001 --num_class 86 --keypoints_number 71 --num_epoch 5 --training_set_path ../../../cristian/dataset_original/WLASL--mediapipe-Train.hdf5 --testing_set_path ../../../cristian/dataset_original/WLASL--mediapipe-Val.hdf5 --config config/sign/train/train_joint.yaml 
python main.py --experiment_name results/f_71/WLASL/cris_openpose_WLASL --database WLASL --keypoints_model openpose --base_lr 0.001 --num_class 86 --keypoints_number 71 --num_epoch 5 --training_set_path ../../../cristian/dataset_original/WLASL--openpose-Train.hdf5 --testing_set_path ../../../cristian/dataset_original/WLASL--openpose-Val.hdf5 --config config/sign/train/train_joint.yaml 


python main.py --experiment_name results/f_71/AEC/cris_wholepose_AEC --database AEC --keypoints_model wholepose --base_lr 0.001 --num_class 28 --keypoints_number 71 --num_epoch 5 --training_set_path ../../../cristian/dataset_original/AEC--wholepose-Train.hdf5 --testing_set_path ../../../cristian/dataset_original/AEC--wholepose-Val.hdf5 --config config/sign/train/train_joint.yaml 
python main.py --experiment_name results/f_71/AEC/cris_mediapipe_AEC --database AEC --keypoints_model mediapipe --base_lr 0.001 --num_class 28 --keypoints_number 71 --num_epoch 5 --training_set_path ../../../cristian/dataset_original/AEC--mediapipe-Train.hdf5 --testing_set_path ../../../cristian/dataset_original/AEC--mediapipe-Val.hdf5 --config config/sign/train/train_joint.yaml 
python main.py --experiment_name results/f_71/AEC/cris_openpose_AEC --database AEC --keypoints_model openpose --base_lr 0.001 --num_class 28 --keypoints_number 71 --num_epoch 5 --training_set_path ../../../cristian/dataset_original/AEC--openpose-Train.hdf5 --testing_set_path ../../../cristian/dataset_original/AEC--openpose-Val.hdf5 --config config/sign/train/train_joint.yaml 
'''

########## tunning ###########71

python main.py --experiment_name results/f_71/AEC/cris_wholepose_AEC --mode_train tunning --database AEC --keypoints_model wholepose --base_lr 0.05 --num_class 28 --keypoints_number 71 --num_epoch 2 --training_set_path ../../../cristian/dataset_original/AEC--wholepose-Train.hdf5 --testing_set_path ../../../cristian/dataset_original/AEC--wholepose-Val.hdf5 --config config/sign/train/train_joint.yaml 
python main.py --experiment_name results/f_71/AEC/cris_wholepose_AEC --mode_train tunning --database AEC --keypoints_model wholepose --base_lr 0.01 --num_class 28 --keypoints_number 71 --num_epoch 2 --training_set_path ../../../cristian/dataset_original/AEC--wholepose-Train.hdf5 --testing_set_path ../../../cristian/dataset_original/AEC--wholepose-Val.hdf5 --config config/sign/train/train_joint.yaml 
python main.py --experiment_name results/f_71/AEC/cris_wholepose_AEC --mode_train tunning --database AEC --keypoints_model wholepose --base_lr 0.005 --num_class 28 --keypoints_number 71 --num_epoch 2 --training_set_path ../../../cristian/dataset_original/AEC--wholepose-Train.hdf5 --testing_set_path ../../../cristian/dataset_original/AEC--wholepose-Val.hdf5 --config config/sign/train/train_joint.yaml 
python main.py --experiment_name results/f_71/AEC/cris_wholepose_AEC --mode_train tunning --database AEC --keypoints_model wholepose --base_lr 0.001 --num_class 28 --keypoints_number 71 --num_epoch 2 --training_set_path ../../../cristian/dataset_original/AEC--wholepose-Train.hdf5 --testing_set_path ../../../cristian/dataset_original/AEC--wholepose-Val.hdf5 --config config/sign/train/train_joint.yaml 
python main.py --experiment_name results/f_71/AEC/cris_wholepose_AEC --mode_train tunning --database AEC --keypoints_model wholepose --base_lr 0.0005 --num_class 28 --keypoints_number 71 --num_epoch 2 --training_set_path ../../../cristian/dataset_original/AEC--wholepose-Train.hdf5 --testing_set_path ../../../cristian/dataset_original/AEC--wholepose-Val.hdf5 --config config/sign/train/train_joint.yaml 
python main.py --experiment_name results/f_71/AEC/cris_wholepose_AEC --mode_train tunning --database AEC --keypoints_model wholepose --base_lr 0.0001 --num_class 28 --keypoints_number 71 --num_epoch 2 --training_set_path ../../../cristian/dataset_original/AEC--wholepose-Train.hdf5 --testing_set_path ../../../cristian/dataset_original/AEC--wholepose-Val.hdf5 --config config/sign/train/train_joint.yaml 

python main.py --experiment_name results/f_71/WLASL/cris_mediapipe_WLASL --mode_train tunning --database WLASL --keypoints_model mediapipe --base_lr 0.05 --num_class 86 --keypoints_number 71 --num_epoch 2 --training_set_path ../../../cristian/dataset_original/WLASL--mediapipe-Train.hdf5 --testing_set_path ../../../cristian/dataset_original/WLASL--mediapipe-Val.hdf5 --config config/sign/train/train_joint.yaml 
python main.py --experiment_name results/f_71/WLASL/cris_mediapipe_WLASL --mode_train tunning --database WLASL --keypoints_model mediapipe --base_lr 0.01 --num_class 86 --keypoints_number 71 --num_epoch 2 --training_set_path ../../../cristian/dataset_original/WLASL--mediapipe-Train.hdf5 --testing_set_path ../../../cristian/dataset_original/WLASL--mediapipe-Val.hdf5 --config config/sign/train/train_joint.yaml 
python main.py --experiment_name results/f_71/WLASL/cris_mediapipe_WLASL --mode_train tunning --database WLASL --keypoints_model mediapipe --base_lr 0.005 --num_class 86 --keypoints_number 71 --num_epoch 2 --training_set_path ../../../cristian/dataset_original/WLASL--mediapipe-Train.hdf5 --testing_set_path ../../../cristian/dataset_original/WLASL--mediapipe-Val.hdf5 --config config/sign/train/train_joint.yaml 
python main.py --experiment_name results/f_71/WLASL/cris_mediapipe_WLASL --mode_train tunning --database WLASL --keypoints_model mediapipe --base_lr 0.001 --num_class 86 --keypoints_number 71 --num_epoch 2 --training_set_path ../../../cristian/dataset_original/WLASL--mediapipe-Train.hdf5 --testing_set_path ../../../cristian/dataset_original/WLASL--mediapipe-Val.hdf5 --config config/sign/train/train_joint.yaml 
python main.py --experiment_name results/f_71/WLASL/cris_mediapipe_WLASL --mode_train tunning --database WLASL --keypoints_model mediapipe --base_lr 0.0005 --num_class 86 --keypoints_number 71 --num_epoch 2 --training_set_path ../../../cristian/dataset_original/WLASL--mediapipe-Train.hdf5 --testing_set_path ../../../cristian/dataset_original/WLASL--mediapipe-Val.hdf5 --config config/sign/train/train_joint.yaml 
python main.py --experiment_name results/f_71/WLASL/cris_mediapipe_WLASL --mode_train tunning --database WLASL --keypoints_model mediapipe --base_lr 0.0001 --num_class 86 --keypoints_number 71 --num_epoch 2 --training_set_path ../../../cristian/dataset_original/WLASL--mediapipe-Train.hdf5 --testing_set_path ../../../cristian/dataset_original/WLASL--mediapipe-Val.hdf5 --config config/sign/train/train_joint.yaml 

python main.py --experiment_name results/f_29/PUCP/cris_openpose_PUCP --mode_train tunning --database PUCP --keypoints_model openpose --base_lr 0.05 --num_class 29 --keypoints_number 71 --num_epoch 2 --training_set_path ../../../cristian/dataset_original/PUCP_PSL_DGI156--openpose-Train.hdf5 --testing_set_path ../../../cristian/dataset_original/PUCP_PSL_DGI156--openpose-Val.hdf5 --config config/sign/train/train_joint.yaml 
python main.py --experiment_name results/f_29/PUCP/cris_openpose_PUCP --mode_train tunning --database PUCP --keypoints_model openpose --base_lr 0.01 --num_class 29 --keypoints_number 71 --num_epoch 2 --training_set_path ../../../cristian/dataset_original/PUCP_PSL_DGI156--openpose-Train.hdf5 --testing_set_path ../../../cristian/dataset_original/PUCP_PSL_DGI156--openpose-Val.hdf5 --config config/sign/train/train_joint.yaml 
python main.py --experiment_name results/f_29/PUCP/cris_openpose_PUCP --mode_train tunning --database PUCP --keypoints_model openpose --base_lr 0.005 --num_class 29 --keypoints_number 71 --num_epoch 2 --training_set_path ../../../cristian/dataset_original/PUCP_PSL_DGI156--openpose-Train.hdf5 --testing_set_path ../../../cristian/dataset_original/PUCP_PSL_DGI156--openpose-Val.hdf5 --config config/sign/train/train_joint.yaml 
python main.py --experiment_name results/f_29/PUCP/cris_openpose_PUCP --mode_train tunning --database PUCP --keypoints_model openpose --base_lr 0.001 --num_class 29 --keypoints_number 71 --num_epoch 2 --training_set_path ../../../cristian/dataset_original/PUCP_PSL_DGI156--openpose-Train.hdf5 --testing_set_path ../../../cristian/dataset_original/PUCP_PSL_DGI156--openpose-Val.hdf5 --config config/sign/train/train_joint.yaml 
python main.py --experiment_name results/f_29/PUCP/cris_openpose_PUCP --mode_train tunning --database PUCP --keypoints_model openpose --base_lr 0.0005 --num_class 29 --keypoints_number 71 --num_epoch 2 --training_set_path ../../../cristian/dataset_original/PUCP_PSL_DGI156--openpose-Train.hdf5 --testing_set_path ../../../cristian/dataset_original/PUCP_PSL_DGI156--openpose-Val.hdf5 --config config/sign/train/train_joint.yaml 
python main.py --experiment_name results/f_29/PUCP/cris_openpose_PUCP --mode_train tunning --database PUCP --keypoints_model openpose --base_lr 0.0001 --num_class 29 --keypoints_number 71 --num_epoch 2 --training_set_path ../../../cristian/dataset_original/PUCP_PSL_DGI156--openpose-Train.hdf5 --testing_set_path ../../../cristian/dataset_original/PUCP_PSL_DGI156--openpose-Val.hdf5 --config config/sign/train/train_joint.yaml 
